# Results
```{r, message=FALSE, include=FALSE}
library(tidyverse)
library(remotes)
library(GGally)
library(parcoords)
library(htmlwidgets)
library(d3r)
library(MASS)
library(treemap)
library(vcd)
library(ggmosaic)
library(lubridate)
library(ggalluvial)
library(gridExtra)
library(RColorBrewer)
library(ggridges)
```

## Top Tags over time



```{r}
df1_count <- df1 %>%
  group_by(year, Tags) %>%
  summarise(TotalViews = sum(ViewCount), TagCount = length(Tags), TotalComments = sum(CommentCount), AcceptedAnswers = sum(as.integer(as.character(AcceptAnswer))), TotalAnswers = sum(AnswerCount)) %>%
  mutate(TagRank = as.factor(order(TagCount,year,Tags, decreasing = T))) 
```
```{r}
initial_rank <- df1_count %>% filter(year==2015) %>% dplyr::select(Tags, TagRank)
initial_rank <- initial_rank %>% rename(InitialRank = TagRank)
initial_rank <- initial_rank[,2:3] 

df1_count <- left_join(df1_count, initial_rank) %>%
  mutate(InitialRank = cut(as.numeric(InitialRank), breaks = seq(0,75,5), right = F))
```
```{r, fig.height=8, fig.width=20, message=FALSE, warning=FALSE}
p <- ggpairs(df1_count %>% dplyr::select(year,TotalViews,TagCount,TotalComments, AcceptedAnswers,TotalAnswers), aes(color=year)) + 
  theme_bw() +
  theme_update(text = element_text(size=15))


#scale colors
for(i in 1:p$nrow) {
  for(j in 1:p$ncol){
    p[i,j] <- p[i,j] + 
        scale_fill_manual(values=rev(c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D"))) +
        scale_color_manual(values=rev(c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D")))  
  }
}

p
#TagCount, TotalComments, AcceptedAnswers, and TotalAnswers are all heavily correlated. Only need to use one or two to monitor the popularity of tags over years 
```
```{r}
grid.arrange(
df1_count %>%
  dplyr::select(year, TotalComments, AcceptedAnswers, TotalAnswers) %>% 
  group_by(year) %>% 
  summarise_all(sum) %>%
  gather("Type","Value",-year) %>%
  ggplot(aes(year, Value, fill = Type)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual("legend", values = c("TotalComments" = "#0072B2", "AcceptedAnswers" = "#D55E00", "TotalAnswers" = "#CC79A7")) +
  theme_bw() +
  ggtitle("Sum of Variables by Year"),
df1_count %>%
  dplyr::select(year, TotalViews) %>% 
  group_by(year) %>% 
  summarise_all(sum) %>%
  gather("Type","Value",-year) %>%
  ggplot(aes(year, Value, fill = Type)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual("legend", values = c("TotalViews" = "#E69F00")) +
  theme_bw(),ncol=1)
#It appears views accumulate over time, total popularity/usage of tag may have to be computed overall. Current usage of Tag not reflected in views. Answers accumulate over time to a lesser degree. AcceptedAnswers seem to be pretty stable but haven't had time to fully accumulate for past 2 years.
```
```{r, fig.height=25, fig.width=30}

getPalette = colorRampPalette(brewer.pal(9, "BuGn"))

df1_count$Ranking<-cut(as.numeric(df1_count$TagRank), seq(0,75,5), right=FALSE)
colourCount = length(unique(df1_count$Ranking))

ggplot(df1_count,
       aes(x = year, stratum = TagRank, alluvium = Tags,
           fill = InitialRank, label = Tags)) +
  scale_fill_manual(values = rev(getPalette(colourCount))) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  geom_flow(stat = "alluvium", lode.guidance = "frontback",
            color = "darkgray") +
  geom_stratum(width = 3/7) +
  geom_text(stat = "alluvium", aes(label = after_stat(alluvium)), size=8) +
  theme(legend.position = "bottom", axis.text = element_text(size = 15, face = "bold")) +
  ggtitle("Frequency of Tags by Year") 
#Tags being used in new posts change drastically in popularity over time. Some notable trends include; amazon-web-services staying in the same rank over several years, android maintained rank for 3 years from 2018 to 2020
```





```{r,fig.height=10, fig.width=20}
treemap(df1_count, index = c("year", "Tags"), vSize = "TagCount" )
treemap(df1_count, index = c("year", "Tags"), vSize = "AcceptedAnswers" )
#nearly identical but with notable differences; python and javascript always have a large proportion 
```