# Interactive component

```{r, fig.height=10, fig.width=16}
df1_count <- df1_count %>% dplyr::select(Tags,year, TotalViews, TagCount, TotalComments, AcceptedAnswers, TagRank) %>%
  mutate(year = as.factor(year))
parcoords(df1_count, rownames = FALSE,
          brushMode = "1D-axes",
          reorderable = TRUE,
          queue = TRUE,
          alpha = 0.5,
          color = list(colorBy = "TagRank", colorScale = "scaleOrdinal", colorScheme = "schemeCategory10"),
          withD3 = TRUE)



```


```{r}
# <head>
# <title>d3.js Canvas Parallel Coordinates</title>
# <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
# <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
# <script src="http://underscorejs.org/underscore-min.js"></script>
# <script src="_include/js/lib/d3.parcoords.js"></script>
# <script src="_include/js/lib/d3.underscore.math.js"></script>
# <script src="_include/js/lib/d3.divgrid.js"></script>
# <link rel="stylesheet" href="_include/css/fonts/droid.css" type="text/css" charset="utf-8" />
# <link href="_include/css/d3.parcoords.css" rel="stylesheet">
# <link href="_include/css/bigdata.parallelcoordinates.css" rel="stylesheet">
# </head>
# <body>
# <button id="keep-data">Keep</button>
# <button id="exclude-data">Exclude</button>
# <button id="reset-data">Reset</button>
# <br>
# <div id="wrapper" class="parcoords" style="width:100%;height:340px">
# <div id="desc">
# <div id="title"><span class="large">Parallel Coordinates</span></div>
# <br>
# a d3.js visualisation using data from Stack Overflow
# <br><br>Drag around axis to begin brush<br>
# Click axis to clear brush<br>Click a label to color data by z-scores
# </div>
# </div>
# </body>
# <div id="grid"></div>
# <script type="text/javascript" src="_include/js/bigdata.parallelcoordinates.js"></script>
```

